/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Jugador;
import civitas.OperacionesJuego;
import civitas.TituloPropiedad;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//import DiarioDialog;
//import Respuestas;
/**
 *
 * @author jesus
 */
public class CivitasView extends javax.swing.JFrame {

    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        
        //Creo una instancia de los jdialog
        DiarioDialog.createInstance(this);
        GestionDialog.createInstance(this);
          
        //Ocultar ranking
        jTextAreaRanking.setVisible(false);
        jLabelRanking.setVisible(false);
        jScrollPane3.setVisible(false);
        
        //Inicializar el panel de jugador
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        
        //Interfaz
        setVisible(true);
        setResizable(false);
        setLocationRelativeTo(null);
        
        //Actualizar
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        jPanelCasillaActual = new javax.swing.JPanel();
        jLabelSigOpTitulo = new javax.swing.JLabel();
        jTextFieldSiguienteOp = new javax.swing.JTextField();
        jLabelRanking = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRanking = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCasillaActual = new javax.swing.JTextArea();
        jLabelCasillaActualTitulo = new javax.swing.JLabel();
        jLabelJugadorActualTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Laksaman", 1, 24)); // NOI18N
        titulo.setText("Civitas");
        titulo.setEnabled(false);

        javax.swing.GroupLayout jPanelCasillaActualLayout = new javax.swing.GroupLayout(jPanelCasillaActual);
        jPanelCasillaActual.setLayout(jPanelCasillaActualLayout);
        jPanelCasillaActualLayout.setHorizontalGroup(
            jPanelCasillaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        jPanelCasillaActualLayout.setVerticalGroup(
            jPanelCasillaActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jLabelSigOpTitulo.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jLabelSigOpTitulo.setText("Siguiente Operación");
        jLabelSigOpTitulo.setEnabled(false);

        jTextFieldSiguienteOp.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jTextFieldSiguienteOp.setText("Operacion");
        jTextFieldSiguienteOp.setEnabled(false);
        jTextFieldSiguienteOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiguienteOpActionPerformed(evt);
            }
        });

        jLabelRanking.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        jLabelRanking.setText("Ranking");
        jLabelRanking.setEnabled(false);

        jTextAreaRanking.setColumns(20);
        jTextAreaRanking.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jTextAreaRanking.setRows(5);
        jTextAreaRanking.setText("Muestro el ranking aqui");
        jTextAreaRanking.setEnabled(false);
        jScrollPane3.setViewportView(jTextAreaRanking);

        jTextAreaCasillaActual.setColumns(20);
        jTextAreaCasillaActual.setRows(5);
        jTextAreaCasillaActual.setText("Informacion de la casilla actual");
        jTextAreaCasillaActual.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaCasillaActual);

        jLabelCasillaActualTitulo.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        jLabelCasillaActualTitulo.setText("Casilla Actual");
        jLabelCasillaActualTitulo.setEnabled(false);

        jLabelJugadorActualTitulo.setFont(new java.awt.Font("Laksaman", 1, 15)); // NOI18N
        jLabelJugadorActualTitulo.setText("Jugador Actual");
        jLabelJugadorActualTitulo.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabelCasillaActualTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJugadorActualTitulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabelSigOpTitulo)
                                        .addGap(16, 16, 16)
                                        .addComponent(jTextFieldSiguienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(99, 99, 99)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(jLabelRanking)))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelCasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCasillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelJugadorActualTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabelCasillaActualTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelSigOpTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jTextFieldSiguienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelRanking))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSiguienteOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiguienteOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiguienteOpActionPerformed

    void setCivitasJuego (CivitasJuego juego){
        this.juego = juego;
        setVisible(true);
    }
    
    //----------------------------------------------------
    //Actualizar vista
    //Jugador casilla ranking
    void actualizarVista (){
        jugadorPanel.setJugador(juego.getJugadorActual());
        actualizarCasilla();
        
        if (juego.finalDelJuego()){
            mostrarRanking();
        }
        
        repaint();
        revalidate();
    }
    
    private void mostrarRanking(){
        //Visibilizo
        jLabelRanking.setVisible(true);
        jScrollPane3.setVisible(true);
        jTextAreaRanking.setVisible(true);
        
        //Edito el texto
        jTextAreaRanking.setText(juego.getRanking());
    }
    
    private void actualizarCasilla(){
        jLabelCasillaActualTitulo.setText("Casilla actual:");
        jTextAreaCasillaActual.setText(juego.getCasillaActual().toString());
    }
   
    //------------------------------------------------
    //Siguiente OP
    void mostrarSiguienteOperacion(OperacionesJuego op){
        jTextFieldSiguienteOp.setText(op.name());
//        actualizarVista();
    }
    
    //-----------------------------------------------
    //Diario
    void mostrarEventos(){
        DiarioDialog.getInstance().mostrarEventos();
    }
    
    //-------------------------------------------------
    //Pausa
    void pausaCambioTurno() {
        JOptionPane.showMessageDialog(this, "Paso de turno");
    }
    
    //--------------------------------------------------
    //Comprar
    Respuestas comprar(){
        int opcion = JOptionPane.showConfirmDialog( 
                                       null, 
                                       "¿Quieres comprar la calle actual?",
                                       "Compra",
                                        JOptionPane.YES_NO_OPTION
                                      );
        
        //Opcion --> 0 SI  | 1 NO
        return Respuestas.values()[opcion];
    }
    
    
    //--------------------------------------------------
    //Gestion
    int getGestion(){
        return GestionDialog.getInstance().getGestion();
    }
    
    int getPropiedad(){
        return GestionDialog.getInstance().getPropiedad();
    }
   
    private ArrayList<String> getPropiedadesString(Jugador jugador){
        ArrayList<TituloPropiedad> p =jugador.getPropiedades();
        ArrayList<String> pNombres = new ArrayList<>();
        
        for (TituloPropiedad t: p)
            pNombres.add(t.getNombre());
        
        return pNombres;
    }
    
    void gestionar(Jugador jugador){
        ArrayList<String> pNombres = getPropiedadesString (jugador);
        GestionDialog.getInstance().gestionar(pNombres);
    }
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CivitasView().setVisible(true);
//            }
//        });
//    }

    //--------------------------------------------------------------
    private JugadorPanel jugadorPanel;
    private CivitasJuego juego;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JLabel jLabelCasillaActualTitulo;
    private javax.swing.JLabel jLabelJugadorActualTitulo;
    private javax.swing.JLabel jLabelRanking;
    private javax.swing.JLabel jLabelSigOpTitulo;
    private javax.swing.JPanel jPanelCasillaActual;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaCasillaActual;
    private javax.swing.JTextArea jTextAreaRanking;
    private javax.swing.JTextField jTextFieldSiguienteOp;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}

