/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.TituloPropiedad;
/**
 *
 * @author jesus
 */
class PropiedadPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadPanel
     */
    PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCasasYHoteles = new javax.swing.JTextField();
        jTextFieldHipotecada = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCasasYHoteles = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelHipotecada = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldCasasYHoteles.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jTextFieldCasasYHoteles.setText("jTextField2");
        jTextFieldCasasYHoteles.setEnabled(false);
        add(jTextFieldCasasYHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, 33));

        jTextFieldHipotecada.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jTextFieldHipotecada.setText("jTextField3");
        jTextFieldHipotecada.setEnabled(false);
        add(jTextFieldHipotecada, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 119, -1, 31));

        titulo.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        titulo.setText("Propiedad");
        titulo.setEnabled(false);
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jLabelNombre.setText("Nombre");
        jLabelNombre.setEnabled(false);
        add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, -1, -1));

        jLabelCasasYHoteles.setText("Casas y Hoteles");
        jLabelCasasYHoteles.setEnabled(false);
        add(jLabelCasasYHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 87, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jTextFieldNombre.setText("jTextField1");
        jTextFieldNombre.setEnabled(false);
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 44, -1, 30));

        jLabelHipotecada.setFont(new java.awt.Font("Laksaman", 0, 15)); // NOI18N
        jLabelHipotecada.setText("Hipotecada");
        jLabelHipotecada.setEnabled(false);
        add(jLabelHipotecada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    //---------------------------------------------------------
    //Métodos
    void setPropiedad(TituloPropiedad titulo){
        tituloPropiedad = titulo;
        
        //Actualizar texto
        int num = titulo.cantidadCasasHoteles();
        String hipotecada = (titulo.getHipotecado())? "SI" : "NO";
        
        this.jTextFieldNombre.setText(titulo.getNombre());
        this.jTextFieldCasasYHoteles.setText(Integer.toString(num));
        this.jTextFieldHipotecada.setText(hipotecada);
    }

    //---------------------------------------------------------
    //Atributos
    private TituloPropiedad tituloPropiedad;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCasasYHoteles;
    private javax.swing.JLabel jLabelHipotecada;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldCasasYHoteles;
    private javax.swing.JTextField jTextFieldHipotecada;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
